config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'framework', to: 'users/registrations#new_framework'
    post 'framework', to: 'users/registrations#create_framework'
  end
  root to:'users#index'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships,       only: [:create, :destroy]
  resources :rooms,               only: [:index, :new, :create, :destroy] do
    resources :messages,          only: [:index,  :create]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :image
  has_one :framework
  has_many :messages
  
  has_many :user_rooms
  has_many :rooms, through: :user_rooms

  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  has_many :followings, through: :following_relationships
  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships

  validates :nickname, presence: true, uniqueness: true
  
  def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
  end

  def follow!(other_user)
    following_relationships.create!(following_id: other_user.id)
  end

  def unfollow!(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end
  
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(sign_up_params)
     unless @user.valid?
       render :new and return
     end
    session["devise.regist_data"] = {user: @user.attributes}
    session["devise.regist_data"][:user]["password"] = params[:user][:password]
    @framework = @user.build_framework
    render :new_framework
  end

  def create_framework
    @user = User.new(session["devise.regist_data"]["user"])
    @framework = Framework.new(framework_params)
    
     unless @framework.valid?
       render :new_framework and return
     end
    @user.build_framework(@framework.attributes)
    @user.save
    session["devise.regist_data"]["user"].clear
    sign_in(:user, @user)
    redirect_to root_path
  end

  private

  def framework_params
    params.require(:framework).permit(:framework_id)
  end
  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def following
    @user  = User.find(params[:id])
    @users = @user.followings
    render 'show_follow'
  end

  def followers
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'show_follower'
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<%= form_for(current_user.following_relationships.build(following_id: @user.id)) do |f| %>
  <div><%= f.hidden_field :following_id %></div>
  <%= f.submit "Follow", class: "btn btn-large btn-primary follow-btn" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user == @user %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>  

app/views/users/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <div class='followings'>
    <strong id="following" class="stat">
      <%= @user.followings.count %>
    </strong>
    <%=link_to 'フォロー', following_user_path(@user), class: 'link' %>
  </div>
  <div class='followers'>
      <strong id="followers" class="stat">
        <%= @user.followers.count %>
      </strong>
      <%= link_to 'フォロワー', followers_user_path(@user), class: 'link' %>
  </div>
</div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.following_relationships.find_by(following_id: @user.id), html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-large follow-btn" %>
<% end %>

app/views/users/index.html.erb
<%= render "shared/header" %>
<div class='wrappe'>
  <div class='announce'>
    <h2>NEWS</h2>
    <div class='announce-list'>
      <dl>
        <dt>2016.8.13</dt>
        <dd>不具合の修正報告</dd>
        <dt>2017.8.12</dt>
        <dd>不具合のお知らせ</dd>
        <dt>2018.8.11</dt>
        <dd>サイトOPNEのお知らせ</dd>
      </dl>
    </div>
  </div>
  <div class='diary-group'>
    <div class='pick-up-diarys'>
      <h3>Pick Up<h3>
    </div>
    <div class='new-diarys'>
      <h3>New Diary</h3>
    </div>
  </div>
</div>
<%= render "shared/footer" %>

app/views/users/show.html.erb
<% case @user.framework.framework_id %>
  <% when 1 %>
    <%= stylesheet_link_tag "framework/simple", :media => "all" %>
  <% when 2 %>
    <%= stylesheet_link_tag "framework/colk", :media => "all" %>
  <% when 3 %>
    <%= stylesheet_link_tag "framework/cat", :media => "all" %>
<% end %> 
<%= render "shared/header" %>
<div class='wrapper'>
    <div class='user-info'>
      <div class='image-rap'>
        <% if @user.image.present? %>
          <%= image_tag user.image, class: 'user-image' if current_user.image.attached? %>
        <% else %>
          <%= image_tag "logo.png", class: 'user-image'%>
        <% end%>
        <%= render "follow_form" %>
        <%= render "stats" %>
      </div>
      <div class='user-rap'>
        <P>マイページ編集</p>
        <p>メッセージ</p>
        <div claa='user-show'>
          <span class='user-show-name'><%= @user.nickname %>さんの詳細</span>
          <p><span class='info'>年齢 :</span> <%= @user.age %></p>
          <p><span class='info'>性別 :</span> <%= @user.gender %></p>
        </div>
      </div>
    </div>
    <div class='right-content'>
      <div class ='user-comment'>
        <p>コメント</p>
      </div>
      <div class='diary-list'>
        <p>投稿日記</p>
      </div>
    </div>
</div>
<%= render "shared/footer" %>

app/views/users/show_follow.html.erb
<% @user.followings.each do |user| %>
<table>
<tr>
  <td>  <%= user.nickname %> </td>
  <td><%= link_to '詳細', user_path(user) %></td>
</tr>

</table>
<% end %>

app/views/users/show_follower.html.erb
<% @user.followers.each do |user| %>
<table>
<tr>
  <td>  <%= user.nickname %> </td>
  <td><%= link_to '詳細', user_path(user) %></td>
</tr>

</table>
<% end %>